### ISSUE TITLE
getfeature() is not defined?

### ISSUE THREAD

**Issue by dieguico** [karimbahgat/PyGeoj#2]
Hi Karim,

There is something wrong with getfeature() ;)

>testfile.getfeature(2)
>
>AttributeError                            Traceback (most recent call last)
><ipython-input-296-0efc8a7d45b6> in <module>()
>----> 1 testfile.getfeature(2)
>
>AttributeError: GeojsonFile instance has no attribute 'getfeature'

Best,

Diego

**Comment by karimbahgat** [comment]
Correct. I assume you were using PyGeoj v0.1? In v0.2 which I published a few days ago, I removed getfeature, as well as insertfeature, removefeature, replacefeature. I felt they were maybe unnecessary and that the same could be done with indexing instead. 

The only feature specific methods I have kept is add_feature(which I like) and pop_feature (which I dont like). I am actually uncertain about this move and am looking for a better solution, so curious to hear your opinion? I was thinking maybe to have user access all features though a .features attribute that refers to a list. In that case I think I might keep add_feature() because that is more convenient than creating a feature and then adding to list.

**Comment by dieguico** [comment]
I'm using v0.2. I just followed the Readme file. There is a getfeature in there. ;)

**Comment by karimbahgat** [comment]
Not sure how i missed that :p Thanks though, will change and update.

**Comment by karimbahgat** [comment]
Removed the getfeature() from the readme, and updated to new version on PyPi. Also brought back a few methods that use better syntax spacing. See #1 .
